---
# - name: "Creates backend app directory"
#   file:
#     path: ~/backend_app
#     state: directory

- name: "Copy compiled backend app"
  become: true
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu

- name: "Unzip backend files to correct directory"
 
  shell: |
      cd /home/ubuntu
      tar -xzvf backend.tar.gz 

- name: "Install dependencies for project"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install pm2 -g
    npm install
    npm run build
- name: "Executing node"
  become: true
  shell: |
    export
    cd /home/ubuntu/backend
    pm2 start --name api  npm -- run start
  register: execute_node
