---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: dist.zip
    dest: "~/backend_app/dist.zip"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    unzip dist.zip
    rm -rf dist.zip
- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install
- name: "Executing node"
  shell: |
    export
    cd ~/backend_app
    pm2 start  npm -- run start:prod
  register: execute_node

