---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Install Node
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    npm run build
    pm2 start npm --name backend -- start:prod

- name: Copy backend dist files web server
  become: true
  copy:
    src: /root/project/backend/dist
    dest: /home/ubuntu    