---
# - name: "Creates backend app directory"
#   file:
#     path: ~/backend_app
#     state: directory

- name: "Copy compiled backend app"
  become: true
  copy:
    src: backend.tar.gz
    dest: /home/ubuntu

- name: "Unzip backend files to correct directory"

  shell: |
      cd /home/ubuntu
      tar -xzvf backend.tar.gz
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present   

- name: "Install dependencies for project"
  shell: |
    cd /home/ubuntu/backend
    npm install pm2 -g
    npm install
    npm run build
    pm2 ls
    pm2 start --name api  npm -- run start

# - name: "Executing node"
#   shell: |
#     cd /home/ubuntu/backend

#   register: execute_node
